output_dir: null
seed: 42

methods:
  - DivBS
  - Uniform

method_opt:
  epoch_selection: True
  iter_selection: False
  num_epochs_per_selection: 5
  ratio: 0.5
  balance: True
  ratio_scheduler: constant
  warmup_epochs: 5
  replace: False

dataset:
  name: CIFAR100
  root: ./_CIFAR

networks:
  type: ResNet
  params:
    m_type: 'resnet18'
    num_classes: 100

training_opt:
  num_epochs: 20
  num_steps: 300000
  num_data_workers: 4
  batch_size: 320
  test_batch_size: 512
  loss_type: CrossEntropy
  loss_params: {}
  optimizer: SGD
  optim_params:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
  scheduler: multistep
  scheduler_params:
    gamma: 0.1
    milestones: [15, 30]

logger_opt:
  print_iter: 100
